# Generated by Django 4.2.9 on 2024-05-19 15:18

import cloudinary.models
from django.db import migrations
import djangoweb.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[djangoweb.photos.validators.validate_file_less_than_5mb]),
        ),
    ]
