# Generated by Django 4.2.9 on 2024-01-13 14:23

from django.db import migrations, models
import djangoweb.accounts.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_remove_appuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', djangoweb.accounts.managers.AppUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
