# Generated by Django 4.2.9 on 2024-05-14 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
